apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: service-account-key
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault-backend
    kind: SecretStore
  target:
    name: service-account-key-sync
  data:
    - secretKey: credentials
      remoteRef:
        key: kv/gcloud
        property: serviceAccountKey
