apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: drupal-password-key
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault-backend
    kind: SecretStore
  target:
    name: drupal-password-sync
  data:
    - secretKey: drupal-password
      remoteRef:
        key: kv/drupal-password
        property: password
