apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: service-account-key
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault-backend
    kind: SecretStore
  target:
    name: admin-user-password-sync
  data:
    - secretKey: root-user
      remoteRef:
        key: kv/minio-user
        property: root-user
    - secretKey: root-password
      remoteRef:
        key: kv/minio-user
        property: root-password
